apiVersion: serving.knative.dev/v1'
kind: Service
metadata:
  name: helloworld-java-quarkus
spec:
  template:
    spec:
      containers:
        - image: docker.iod/satoshiyamamoto/helloworld-java-quarkus
          env:
            - name: TARGET
              value: "Quarkus Sample v1"